/*
 * JNI bridge between cubeium.cubeium.world.CubiomesInterface and cubiomes.
 *
 * The header below is generated by javac (-h) from CubiomesInterface.java
 * during the Gradle build, so the native signatures and the Java constants
 * can never drift from the Java side unnoticed.
 */

#include "cubeium_cubeium_world_CubiomesInterface.h"

#include "biomes.h"
#include "finders.h"
#include "generator.h"
#include "util.h"

#include <stdint.h>
#include <stdlib.h>

//==============================================================================
// Compile-time checks: Java constants must match the cubiomes enums
//==============================================================================

#define CHECK_CONST(JAVA, C) \
    _Static_assert(cubeium_cubeium_world_CubiomesInterface_##JAVA == (C), \
        "CubiomesInterface." #JAVA " does not match cubiomes " #C)

CHECK_CONST(MC_UNDEF, MC_UNDEF);
CHECK_CONST(MC_B1_7, MC_B1_7);
CHECK_CONST(MC_B1_8, MC_B1_8);
CHECK_CONST(MC_1_0, MC_1_0);
CHECK_CONST(MC_1_1, MC_1_1);
CHECK_CONST(MC_1_2, MC_1_2);
CHECK_CONST(MC_1_3, MC_1_3);
CHECK_CONST(MC_1_4, MC_1_4);
CHECK_CONST(MC_1_5, MC_1_5);
CHECK_CONST(MC_1_6, MC_1_6);
CHECK_CONST(MC_1_7, MC_1_7);
CHECK_CONST(MC_1_8, MC_1_8);
CHECK_CONST(MC_1_9, MC_1_9);
CHECK_CONST(MC_1_10, MC_1_10);
CHECK_CONST(MC_1_11, MC_1_11);
CHECK_CONST(MC_1_12, MC_1_12);
CHECK_CONST(MC_1_13, MC_1_13);
CHECK_CONST(MC_1_14, MC_1_14);
CHECK_CONST(MC_1_15, MC_1_15);
CHECK_CONST(MC_1_16_1, MC_1_16_1);
CHECK_CONST(MC_1_16, MC_1_16);
CHECK_CONST(MC_1_17, MC_1_17);
CHECK_CONST(MC_1_18, MC_1_18);
CHECK_CONST(MC_1_19_2, MC_1_19_2);
CHECK_CONST(MC_1_19, MC_1_19);
CHECK_CONST(MC_1_20, MC_1_20);
CHECK_CONST(MC_1_21_1, MC_1_21_1);
CHECK_CONST(MC_1_21_3, MC_1_21_3);
CHECK_CONST(MC_1_21_4, MC_1_21_4);
CHECK_CONST(MC_1_21_5, MC_1_21_5);
CHECK_CONST(MC_1_21_6, MC_1_21_6);
CHECK_CONST(MC_1_21_9, MC_1_21_9);
CHECK_CONST(MC_1_21_11, MC_1_21_11);
CHECK_CONST(MC_26_1, MC_26_1);
CHECK_CONST(MC_26_2, MC_26_2);
CHECK_CONST(MC_26_3, MC_26_3);
CHECK_CONST(MC_NEWEST, MC_NEWEST);

CHECK_CONST(DIM_NETHER, DIM_NETHER);
CHECK_CONST(DIM_OVERWORLD, DIM_OVERWORLD);
CHECK_CONST(DIM_END, DIM_END);

CHECK_CONST(LARGE_BIOMES, LARGE_BIOMES);
CHECK_CONST(NO_BETA_OCEAN, NO_BETA_OCEAN);
CHECK_CONST(FORCE_OCEAN_VARIANTS, FORCE_OCEAN_VARIANTS);

CHECK_CONST(FEATURE, Feature);
CHECK_CONST(DESERT_PYRAMID, Desert_Pyramid);
CHECK_CONST(JUNGLE_TEMPLE, Jungle_Temple);
CHECK_CONST(SWAMP_HUT, Swamp_Hut);
CHECK_CONST(IGLOO, Igloo);
CHECK_CONST(VILLAGE, Village);
CHECK_CONST(OCEAN_RUIN, Ocean_Ruin);
CHECK_CONST(SHIPWRECK, Shipwreck);
CHECK_CONST(MONUMENT, Monument);
CHECK_CONST(MANSION, Mansion);
CHECK_CONST(OUTPOST, Outpost);
CHECK_CONST(RUINED_PORTAL, Ruined_Portal);
CHECK_CONST(RUINED_PORTAL_NETHER, Ruined_Portal_N);
CHECK_CONST(ANCIENT_CITY, Ancient_City);
CHECK_CONST(TREASURE, Treasure);
CHECK_CONST(MINESHAFT, Mineshaft);
CHECK_CONST(DESERT_WELL, Desert_Well);
CHECK_CONST(GEODE, Geode);
CHECK_CONST(FORTRESS, Fortress);
CHECK_CONST(BASTION, Bastion);
CHECK_CONST(NETHER_FOSSIL, Nether_Fossil);
CHECK_CONST(END_CITY, End_City);
CHECK_CONST(END_GATEWAY, End_Gateway);
CHECK_CONST(END_ISLAND, End_Island);
CHECK_CONST(TRAIL_RUINS, Trail_Ruins);
CHECK_CONST(TRIAL_CHAMBERS, Trial_Chambers);
CHECK_CONST(ABANDONED_CAMP, Abandoned_Camp);
CHECK_CONST(STRONGHOLD, Stronghold);
CHECK_CONST(FEATURE_NUM, FEATURE_NUM);

//==============================================================================
// Helpers
//==============================================================================

#define MAX_GEN_AREA (4096 * 4096)

static void throwNew(JNIEnv *env, const char *className, const char *msg)
{
    jclass cls = (*env)->FindClass(env, className);
    if (cls)
        (*env)->ThrowNew(env, cls, msg);
}

static void throwIllegalArgument(JNIEnv *env, const char *msg)
{
    throwNew(env, "java/lang/IllegalArgumentException", msg);
}

static void throwIllegalState(JNIEnv *env, const char *msg)
{
    throwNew(env, "java/lang/IllegalStateException", msg);
}

static Generator *toGenerator(JNIEnv *env, jlong handle)
{
    if (handle == 0)
    {
        throwIllegalState(env, "generator handle is null (freed or never created)");
        return NULL;
    }
    return (Generator *)(intptr_t) handle;
}

static int isValidVersion(jint mc)
{
    return mc > MC_UNDEF && mc <= MC_NEWEST;
}

static int isValidScale(jint scale)
{
    return scale == 1 || scale == 4 || scale == 16 || scale == 64 || scale == 256;
}

static jintArray newIntArray(JNIEnv *env, const jint *values, jsize len)
{
    jintArray result = (*env)->NewIntArray(env, len);
    if (result)
        (*env)->SetIntArrayRegion(env, result, 0, len, values);
    return result; // NULL with a pending OutOfMemoryError on failure
}

//==============================================================================
// Generator management
//==============================================================================

JNIEXPORT jlong JNICALL Java_cubeium_cubeium_world_CubiomesInterface_setupGenerator
  (JNIEnv *env, jclass cls, jint mcVersion, jint flags)
{
    (void) cls;
    if (!isValidVersion(mcVersion))
    {
        throwIllegalArgument(env, "unsupported Minecraft version");
        return 0;
    }

    Generator *g = malloc(sizeof(Generator));
    if (!g)
    {
        throwNew(env, "java/lang/OutOfMemoryError", "failed to allocate generator");
        return 0;
    }
    setupGenerator(g, (int) mcVersion, (uint32_t) flags);
    return (jlong)(intptr_t) g;
}

JNIEXPORT void JNICALL Java_cubeium_cubeium_world_CubiomesInterface_freeGenerator
  (JNIEnv *env, jclass cls, jlong generator)
{
    (void) env; (void) cls;
    free((Generator *)(intptr_t) generator);
}

JNIEXPORT void JNICALL Java_cubeium_cubeium_world_CubiomesInterface_applySeed
  (JNIEnv *env, jclass cls, jlong generator, jint dimension, jlong seed)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return;
    if (dimension != DIM_OVERWORLD && dimension != DIM_NETHER && dimension != DIM_END)
    {
        throwIllegalArgument(env, "dimension must be -1 (Nether), 0 (Overworld) or 1 (End)");
        return;
    }
    applySeed(g, (int) dimension, (uint64_t) seed);
}

//==============================================================================
// Biomes
//==============================================================================

JNIEXPORT jint JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getBiomeAt
  (JNIEnv *env, jclass cls, jlong generator, jint scale, jint x, jint y, jint z)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return none;
    if (!isValidScale(scale))
    {
        throwIllegalArgument(env, "scale must be 1, 4, 16, 64 or 256");
        return none;
    }
    return getBiomeAt(g, scale, x, y, z);
}

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_genBiomes
  (JNIEnv *env, jclass cls, jlong generator, jint scale, jint x, jint z, jint y, jint width, jint height)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return NULL;
    if (!isValidScale(scale))
    {
        throwIllegalArgument(env, "scale must be 1, 4, 16, 64 or 256");
        return NULL;
    }
    if (width <= 0 || height <= 0 || (int64_t) width * height > MAX_GEN_AREA)
    {
        throwIllegalArgument(env, "area must be non-empty and at most 4096x4096");
        return NULL;
    }

    Range r = { .scale = scale, .x = x, .z = z, .sx = width, .sz = height, .y = y, .sy = 1 };
    int *cache = allocCache(g, r);
    if (!cache)
    {
        throwNew(env, "java/lang/OutOfMemoryError", "failed to allocate biome cache");
        return NULL;
    }

    jintArray result = NULL;
    int err = genBiomes(g, cache, r);
    if (err)
        throwNew(env, "java/lang/RuntimeException", "cubiomes genBiomes failed");
    else
        result = newIntArray(env, (const jint *) cache, width * height);

    free(cache);
    return result;
}

JNIEXPORT jstring JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getBiomeName
  (JNIEnv *env, jclass cls, jint mcVersion, jint biomeId)
{
    (void) cls;
    const char *name = biome2str((int) mcVersion, (int) biomeId);
    return name ? (*env)->NewStringUTF(env, name) : NULL;
}

JNIEXPORT jboolean JNICALL Java_cubeium_cubeium_world_CubiomesInterface_isOverworldBiome
  (JNIEnv *env, jclass cls, jint mcVersion, jint biomeId)
{
    (void) env; (void) cls;
    return isOverworld((int) mcVersion, (int) biomeId) ? JNI_TRUE : JNI_FALSE;
}

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getBiomeColors
  (JNIEnv *env, jclass cls)
{
    (void) cls;
    unsigned char rgb[256][3];
    jint argb[256];
    initBiomeColors(rgb);
    for (int i = 0; i < 256; i++)
        argb[i] = (jint)(0xFF000000u | ((uint32_t) rgb[i][0] << 16) | ((uint32_t) rgb[i][1] << 8) | rgb[i][2]);
    return newIntArray(env, argb, 256);
}

//==============================================================================
// Structures
//==============================================================================

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStructureConfig
  (JNIEnv *env, jclass cls, jint structureType, jint mcVersion)
{
    (void) cls;
    StructureConfig sc;
    if (structureType < 0 || structureType >= FEATURE_NUM || !isValidVersion(mcVersion))
        return NULL;
    if (!getStructureConfig((int) structureType, (int) mcVersion, &sc))
        return NULL;
    jint values[3] = { sc.regionSize, sc.chunkRange, sc.dim };
    return newIntArray(env, values, 3);
}

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStructurePos
  (JNIEnv *env, jclass cls, jint structureType, jint mcVersion, jlong seed, jint regionX, jint regionZ)
{
    (void) cls;
    if (structureType < 0 || structureType >= FEATURE_NUM)
    {
        throwIllegalArgument(env, "unknown structure type");
        return NULL;
    }
    if (!isValidVersion(mcVersion))
    {
        throwIllegalArgument(env, "unsupported Minecraft version");
        return NULL;
    }

    Pos pos;
    if (!getStructurePos((int) structureType, (int) mcVersion, (uint64_t) seed, regionX, regionZ, &pos))
        return NULL; // no generation attempt in this region
    jint values[2] = { pos.x, pos.z };
    return newIntArray(env, values, 2);
}

JNIEXPORT jboolean JNICALL Java_cubeium_cubeium_world_CubiomesInterface_isViableStructurePos
  (JNIEnv *env, jclass cls, jint structureType, jlong generator, jint x, jint z, jint flags)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return JNI_FALSE;
    if (structureType < 0 || structureType >= FEATURE_NUM)
    {
        throwIllegalArgument(env, "unknown structure type");
        return JNI_FALSE;
    }

    if (!isViableStructurePos((int) structureType, g, x, z, (uint32_t) flags))
        return JNI_FALSE;
    // 1.18+: rule out positions where the surface is clearly too low (no-op for other types).
    if (g->dim == DIM_OVERWORLD && !isViableStructureTerrain((int) structureType, g, x, z))
        return JNI_FALSE;
    return JNI_TRUE;
}

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStrongholds
  (JNIEnv *env, jclass cls, jlong generator, jint maxCount)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return NULL;
    if (g->dim != DIM_OVERWORLD)
    {
        throwIllegalState(env, "strongholds require a generator seeded for the Overworld");
        return NULL;
    }
    if (maxCount < 1 || maxCount > 128)
    {
        throwIllegalArgument(env, "maxCount must be between 1 and 128");
        return NULL;
    }

    jint positions[2 * 128];
    int count = 0;
    StrongholdIter sh;
    initFirstStronghold(&sh, g->mc, g->seed);
    while (count < maxCount)
    {
        // nextStronghold() resolves the accurate position of the current
        // stronghold into sh.pos and returns how many strongholds follow it.
        int remaining = nextStronghold(&sh, g);
        positions[2 * count] = sh.pos.x;
        positions[2 * count + 1] = sh.pos.z;
        count++;
        if (remaining <= 0)
            break;
    }
    return newIntArray(env, positions, 2 * count);
}

JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getSpawn
  (JNIEnv *env, jclass cls, jlong generator, jboolean exact)
{
    (void) cls;
    Generator *g = toGenerator(env, generator);
    if (!g)
        return NULL;
    if (g->dim != DIM_OVERWORLD)
    {
        throwIllegalState(env, "spawn requires a generator seeded for the Overworld");
        return NULL;
    }

    Pos spawn = exact ? getSpawn(g) : estimateSpawn(g, NULL);
    jint values[2] = { spawn.x, spawn.z };
    return newIntArray(env, values, 2);
}

JNIEXPORT jstring JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStructureName
  (JNIEnv *env, jclass cls, jint structureType)
{
    (void) cls;
    const char *name = struct2str((int) structureType);
    return name ? (*env)->NewStringUTF(env, name) : NULL;
}
