/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cubeium_cubeium_world_CubiomesInterface */

#ifndef _Included_cubeium_cubeium_world_CubiomesInterface
#define _Included_cubeium_cubeium_world_CubiomesInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    setupGenerator
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_cubeium_cubeium_world_CubiomesInterface_setupGenerator
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    freeGenerator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cubeium_cubeium_world_CubiomesInterface_freeGenerator
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    applySeed
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_cubeium_cubeium_world_CubiomesInterface_applySeed
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getBiomeAt
 * Signature: (JIIIII)I
 */
JNIEXPORT jint JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getBiomeAt
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    genBiomes
 * Signature: (JIIIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_genBiomes
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    genBiomes3D
 * Signature: (JIIIIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_genBiomes3D
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getStructurePos
 * Signature: (IIJII)[I
 */
JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStructurePos
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    isViableStructurePos
 * Signature: (IJIII)Z
 */
JNIEXPORT jboolean JNICALL Java_cubeium_cubeium_world_CubiomesInterface_isViableStructurePos
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getStrongholds
 * Signature: (JJI)[I
 */
JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStrongholds
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getSpawn
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getSpawn
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getBiomeName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getBiomeName
  (JNIEnv *, jclass, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getStructureName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getStructureName
  (JNIEnv *, jclass, jint);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    isLibraryLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cubeium_cubeium_world_CubiomesInterface_isLibraryLoaded
  (JNIEnv *, jclass);

/*
 * Class:     cubeium_cubeium_world_CubiomesInterface
 * Method:    getLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cubeium_cubeium_world_CubiomesInterface_getLibraryVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
